#!/bin/sh
clear
chmod -x BingDownloaderLinux_x86
checkDir=`ls /home/$USER -a | grep ".BingWallpaper"`
if [[ -z $checkDir ]]; then
	echo "Creating My Directory"
	mkdir /home/$USER/.BingWallpaper/ 
fi
cp BingDownloaderLinux_x86 /home/$USER/.BingWallpaper/ #Keep me updated
checkCronEntry=`crontab -l | grep "00 00 \* \* \* bash /home/$USER/.BingWallpaper/"`
if [[ -z $checkCronEntry ]]; then
	echo "scheduling myself"
	(crontab -l ; echo "00 00 * * * bash /home/$USER/.BingWallpaper/BingDownloaderLinux_x86") | crontab
fi
echo "Wait some sec.... Getting your fuzzy freaky bing wallpaper"
wget --header="User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" \
--header="Accept: */*" \
--header="Accept-Language: en-US,en;q=0.5" \
--header="Accept-Encoding: identity" \
--header="Content-Type: text/plain;charset=UTF-8" \
--header="Connection: keep-alive" \
 --user-agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "https://www.bing.com" -O .tmp_file > /dev/null 2>&1
 wpaper=`cat .tmp_file | hxnormalize -x | grep "href=\"/th?id=" | cut -d'"' -f2`
wget --header="User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" \
--header="Accept: */*" \
--header="Accept-Language: en-US,en;q=0.5" \
--header="Accept-Encoding: identity" \
--header="Content-Type: text/plain;charset=UTF-8" \
--header="Connection: keep-alive" \
 --user-agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "https://www.bing.com/$wpaper" -O /home/$USER/.BingWallpaper/.wallpaper > /dev/null 2>&1
gsettings set org.gnome.desktop.background picture-uri file:///home/$USER/.BingWallpaper/.wallpaper
rm .tmp_file